IOT_Management/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from .import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', views.homePage, name="home"),
    path('', include('user.urls')),
    path('dashboard/', include('device.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

device/urls.py
from django.urls import path
from .import views

app_name = 'device'

urlpatterns = [
    path('<slug:slug>/', views.deviceDashboard, name="dashboard"),
]

user/urls.py
from django.urls import path
from .import views

app_name = 'users'

urlpatterns = [
    path('', views.loginPage, name="login"),
    path("signup/", views.signUpPage, name="signup"),
    path('getcode/', views.getOTP, name="resetPass"),
    path('resetPass/', views.resetPass, name="resetPass_1"),
    path('logout/', views.logoutPage, name='logout'),
    path('profile/', views.accountPage, name='profile'),
]

templates/home.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="{% static 'css/home.css' %}">

    <title>
        Home
    </title>

    <style>
        .welcome_block {
            background-image: url('{% static "img/Home_background.svg"%}');
            background-repeat: no-repeat;
            background-size: 100%;

            min-height: 690px;
        }

        .dropdown {
        position: relative;
        display: inline-block;
        }
        
        .dropdown-content {
        display: none;
        position: absolute;
        background-color: #f1f1f1;
        min-width: 160px;
        box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
        z-index: 1;
        }
        
        .dropdown-content a {
        color: black;
        padding: 12px 16px;
        text-decoration: none;
        display: block;
        }
        
        .dropdown-content a:hover {background-color: #ddd;}
        
        .dropdown:hover .dropdown-content {display: block;}
</style>
</head>
<body>
    <div class="welcome_block">
        <div class="d-flex flex-row-reverse">
            <div class="dropdown" style="padding: 10px 30px 10px 0px">
                <img src="{{ user.avatar.url }}" alt="Avatar" class="header_avatar">
                <div class="dropdown-content">
                    <a href="{% url "users:profile" %}">View Account</a>
                    <a href="{% url "users:logout" %}">Logout</a>
                </div>
            </div>
        </div>

        <div class="text-center fw-bold pt-3" style="font-size: 90px; color: #EDE2FF">
            <p>Welcome back</p>
            <p>{{ user.username }}</p>
        </div>
    </div>

    <div class="device_block">
        <br>
        <p class="fw-bold text-center" style="font-size: 60px; color: #EDE2FF">Devices</p>

        <table class="table" style="--bs-table-bg: none">
            <thead>
              <tr>
                <th scope="col" style="color: white">#</th>
                <th scope="col" style="color: white">Device Name</th>
                <th scope="col" style="color: white">Device Type</th>
                <th scope="col" style="color: white">Device Status</th>
              </tr>
            </thead>
            <tbody>
                {% for device in devices %}
                    <tr>
                        <th scope="row" id="table_element" style="padding-top: 1.14%">{{ forloop.counter }}</th>
                        <td id="table_element">
                            <div class="d-flex">
                                <a href="{% url "device:dashboard" slug=device.id %}" style="color: #EDE2FF; text-decoration: none; padding-top: 2%">{{ device.name }}</a>
                                
                                <button class="btn btn-outline-secondary ms-auto" type="button" data-bs-toggle="modal" data-bs-target="#changName" style="--bs-btn-border-color: none">
                                    <i class="bi bi-pencil" style="color: #EDE2FF"></i>
                                </button>

                                <div class="modal fade" id="changName" tabindex="-1" aria-labelledby="deviceLabel" aria-hidden="true" style="color: black">
                                    <div class="modal-dialog modal-dialog-centered">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h1 class="modal-title fs-5" id="deviceLabel">Change device name</h1>
                                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                            </div>
                                            <div class="modal-body">
                                                <form method="POST">
                                                    {% csrf_token %}
                                                    <div class="mb-4">
                                                        <label for="changeDeviceName" class="form-label mb-2" id="form_label">Device Name</label>
                                                        <input type="text" name="new_name" id="changeDeviceName-{{ device.id }}" class="form-control form-control-xl fs-6" required>
                                                    </div>
                                                    
                                                    <button type="submit" name="change_name" value="{{ device.id }}" class="w-100 btn btn-dark btn-md mb-4">Change</button>
                                                </form>
                                            </div>
                                        
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </td>
                        <td id="table_element" style="padding-top: 1.3%">{{ device.type }}</td>
                        <td id="table_element">
                            <div class="d-flex">
                                <p style="padding-top: 1.3%" id="status-{{ device.id }}">Disconnected</p>
                                <form method="POST" class="ms-auto">
                                    {% csrf_token %}
                                    <button name="delete_device" value="{{ device.id }}" class="btn btn-outline-secondary" type="submit" style="--bs-btn-border-color: none">
                                        <i class="bi bi-trash3" style="color: #EDE2FF"></i>
                                    </button>
                                </form>
                            </div>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>

        <div class="d-flex justify-content-center align-items-center">
            <button type="button" class="btn btn-outline-light add_button" data-bs-toggle="modal" data-bs-target="#addModal">
                <i class="bi bi-plus-lg"></i>
            </button>
            <p style="padding-top: 15px; color: #EDE2FF;">Add device</p>
        </div>

        {% if messages %}
            <div class="alert alert-warning alert-dismissible fade show" role="alert">
                {% for message in messages %}
                <strong>Hey! </strong> {{message}}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                {% endfor %}
            </div>
        {% endif %}

        <div class="modal fade" id="addModal" tabindex="-1" aria-labelledby="deviceLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                    <div class="modal-header">
                        <h1 class="modal-title fs-5" id="deviceLabel">Add device</h1>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <form method="POST">
                            {% csrf_token %}
                            <div class="mb-2">
                                <label for="deviceName" class="form-label mb-2" id="form_label">Device Name</label>
                                <input type="text" name="device_name" id="deviceName" class="form-control form-control-xl fs-6" required>
                            </div>
                
                            <div class="mb-4">
                                <label for="id" class="form-label mb-2" id="form_label">Device ID</label>
                                <input type="password" name="device_id" id="id" class="form-control form-control-xl fs-6" required>
                            </div>
                            
                            <button type="submit" class="w-100 btn btn-dark btn-md mb-4">Add</button>
                        </form>
                    </div>
                
                </div>
            </div>
        </div>
    </div>
    <script>
        // Kết nối WebSocket
        const socket = new WebSocket('ws://127.0.0.1:8000/ws/mqtt/front-end');

        // Khi kết nối thành công
        socket.onopen = function () {
            console.log("WebSocket connection established.");
        };

        // Khi nhận được tin nhắn từ server
        socket.onmessage = function (event) {
            let data = JSON.parse(event.data);

            if (data.user == "{{ user.username }}" && data.device_status !== undefined) {
                data = data.device_status
                // Hiển thị trạng thái trên giao diện
                const deviceId = data.device_id;
                const status = data.status;

                // Ví dụ: cập nhật trạng thái thiết bị trên HTML
                const statusElement = document.getElementById(`status-${deviceId}`);
                if (statusElement) {
                    statusElement.textContent = status;
                }
            }
        };

        // Khi WebSocket đóng
        socket.onclose = function () {
            console.log("WebSocket connection closed.");
        };

    </script>
</body>
</html>